name: DessertSpot CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: cd DessertSpot/backend && ./gradlew build

      - name: Run tests with Gradle
        run: cd DessertSpot/backend && ./gradlew test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: DessertSpot/backend/build/test-results/test
